"""Build-time Laya preference mapper.

Laya is intentionally kept out of the realtime PCM thread. This script turns a
natural-language preference into a compact deterministic DSP profile that both
the Android C++ engine and Windows .NET player consume.
"""
from __future__ import annotations
import argparse, json, pathlib

DEFAULT = {
    "minimum_db": -2.0,
    "maximum_db": 5.0,
    "pre_drop_db": -2.0,
    "impact_db": 5.0,
    "lookahead_ms": 80,
    "impact_hold_ms": 70,
    "cooldown_ms": 420,
    "strong_surge_db": 4.5,
    "loud_surge_db": 2.5,
    "pre_duck_ms": 22,
    "impact_attack_ms": 6,
    "impact_release_ms": 180,
    "source": "pinned-harsh-concert",
}

def try_laya(text: str) -> dict:
    try:
        from laya import Router
        router = Router(preload=False, max_loaded=1)
        questions = {
            "shape": {
                "type": "choice",
                "instructions": "What dynamic shape does the listener want?",
                "criteria": {
                    "concert_drop": "brief dip before a loud section, then a sudden impact lift",
                    "smooth_ride": "gradual automatic loudness riding without a dramatic drop",
                    "neutral": "minimal dynamic intervention",
                },
            },
            "aggression": {
                "type": "choice",
                "instructions": "How strong should the requested concert impact feel?",
                "criteria": {
                    "light": "subtle and transparent",
                    "medium": "clearly audible but restrained",
                    "strong": "dramatic DJ or live concert style contrast",
                },
            },
        }
        result = router.predict({"preference": text}, questions, model="typed-decisions")
        answers = result["answers"]
        shape = answers["shape"]["choice"]
        aggression = answers["aggression"]["choice"]
        profile = dict(DEFAULT)
        profile["source"] = "laya-typed-decisions"
        if shape != "concert_drop":
            profile["shape_disagreement"] = shape

        # The user's explicitly chosen -2/+5 dB endpoints are authoritative.
        # Laya only tunes detection sensitivity/timing, never the endpoints.
        if aggression == "light":
            profile.update(strong_surge_db=5.5, loud_surge_db=3.5, lookahead_ms=70, cooldown_ms=500)
        elif aggression == "medium":
            profile.update(strong_surge_db=5.0, loud_surge_db=3.0, lookahead_ms=80, cooldown_ms=460)
        else:
            profile.update(strong_surge_db=4.5, loud_surge_db=2.5, lookahead_ms=80, cooldown_ms=420)
        profile["laya_routing"] = result.get("routing", {})
        return profile
    except Exception as exc:
        p = dict(DEFAULT)
        p["source"] = "fallback-after-laya-error"
        p["laya_error"] = f"{type(exc).__name__}: {exc}"
        return p

def emit_cs(profile: dict, path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f'''namespace LastWaveWindows;\n\n// Auto-generated by tools/generate_laya_profile.py\ninternal static class GeneratedPersonalDjProfile\n{{\n    public const string Source = "{profile["source"]}";\n    public const float MinimumDb = {profile["minimum_db"]:.3f}f;\n    public const float MaximumDb = {profile["maximum_db"]:.3f}f;\n    public const float PreDropDb = {profile["pre_drop_db"]:.3f}f;\n    public const float ImpactDb = {profile["impact_db"]:.3f}f;\n    public const double LookAheadSeconds = {profile["lookahead_ms"] / 1000.0:.6f};\n    public const double ImpactHoldSeconds = {profile["impact_hold_ms"] / 1000.0:.6f};\n    public const double CooldownSeconds = {profile["cooldown_ms"] / 1000.0:.6f};\n    public const float StrongSurgeDb = {profile["strong_surge_db"]:.3f}f;\n    public const float LoudSurgeDb = {profile["loud_surge_db"]:.3f}f;\n    public const double PreDuckSeconds = {profile["pre_duck_ms"] / 1000.0:.6f};\n    public const double ImpactAttackSeconds = {profile["impact_attack_ms"] / 1000.0:.6f};\n    public const double ImpactReleaseSeconds = {profile["impact_release_ms"] / 1000.0:.6f};\n}}\n''', encoding="utf-8")

def emit_cpp(profile: dict, path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f'''#pragma once\n\n// Auto-generated by tools/generate_laya_profile.py\nnamespace lastwave::audio::personal_dj {{\ninline constexpr float kMinimumDb = {profile["minimum_db"]:.3f}F;\ninline constexpr float kMaximumDb = {profile["maximum_db"]:.3f}F;\ninline constexpr float kPreDropDb = {profile["pre_drop_db"]:.3f}F;\ninline constexpr float kImpactDb = {profile["impact_db"]:.3f}F;\ninline constexpr double kLookAheadSeconds = {profile["lookahead_ms"] / 1000.0:.6f};\ninline constexpr double kImpactHoldSeconds = {profile["impact_hold_ms"] / 1000.0:.6f};\ninline constexpr double kCooldownSeconds = {profile["cooldown_ms"] / 1000.0:.6f};\ninline constexpr float kStrongSurgeDb = {profile["strong_surge_db"]:.3f}F;\ninline constexpr float kLoudSurgeDb = {profile["loud_surge_db"]:.3f}F;\ninline constexpr double kPreDuckSeconds = {profile["pre_duck_ms"] / 1000.0:.6f};\ninline constexpr double kImpactAttackSeconds = {profile["impact_attack_ms"] / 1000.0:.6f};\ninline constexpr double kImpactReleaseSeconds = {profile["impact_release_ms"] / 1000.0:.6f};\n}}  // namespace lastwave::audio::personal_dj\n''', encoding="utf-8")

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preference", default="personalization/harsh_dj_preference.txt")
    ap.add_argument("--out", default="personalization/generated_profile.json")
    ap.add_argument("--emit-cs")
    ap.add_argument("--emit-cpp")
    ap.add_argument("--use-laya", action="store_true")
    ns = ap.parse_args()
    text = pathlib.Path(ns.preference).read_text(encoding="utf-8")
    profile = try_laya(text) if ns.use_laya else dict(DEFAULT)
    pathlib.Path(ns.out).parent.mkdir(parents=True, exist_ok=True)
    pathlib.Path(ns.out).write_text(json.dumps(profile, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")
    if ns.emit_cs: emit_cs(profile, pathlib.Path(ns.emit_cs))
    if ns.emit_cpp: emit_cpp(profile, pathlib.Path(ns.emit_cpp))
    print(json.dumps(profile, indent=2, ensure_ascii=False))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
